wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684423690.026102
    t:
      1:
      - 1
      - 9
      - 55
      2:
      - 1
      - 9
      - 55
      3:
      - 7
      - 23
      4: 3.10.6
      5: 0.15.3
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
